### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by traversaro**
README:
* Fix wrong link to Dockerfile in another repo
* Fix repo name

Dockerfile:
* Remove not useful comment at the beginning at dockerfile
* Remove env variables that point to empty variables

### CODE REVIEW

**Comment by traversaro** [comment]
I would also like to switch to install not the latest version of micromamba but a fixed released, but I could not find an easy way to do it.

@CarlottaSartore could it also make sense to save the output of:
~~~
curl -fsSL https://raw.githubusercontent.com/ami-iit/log-installed-software/main/src/log.py | python
~~~

in the image, so that in the future if we have problem we know exactly the version of dependencies resulting in the installation as of October 2023.

**Review by CarlottaSartore — APPROVED** [review]

**Comment by CarlottaSartore** [comment]
Thanks @traversaro , I have merged the PR ! 
Here I attach  the output of the code installed, the docker image was created `2023-07-10` 
[installed_software.txt](https://github.com/ami-iit/paper_sartore_2023_humanoids_codesign-ga-nl/files/13239420/installed_software.txt)
Do you think it is worth to add it directly in the repo ? in case I will open a dedicated PR

**Comment by traversaro** [comment]
> Thanks @traversaro , I have merged the PR ! Here I attach the output of the code installed, the docker image was created `2023-07-10` [installed_software.txt](https://github.com/ami-iit/paper_sartore_2023_humanoids_codesign-ga-nl/files/13239420/installed_software.txt) Do you think it is worth to add it directly in the repo ? in case I will open a dedicated PR

Not sure to be honest, anyhow this issue is public.

**Comment by CarlottaSartore** [comment]
I will keep it here for the time being then!   thanks !

**Pull request merged**
